name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'access-request-system/apps/access-frontend/**'
      - 'access-request-system/libs/access-sdk/**'
      - 'access-request-system/package.json'
      - 'access-request-system/package-lock.json'
  pull_request:
    paths:
      - 'access-request-system/apps/access-frontend/**'
      - 'access-request-system/libs/access-sdk/**'

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: access-request-system
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: access-request-system/package-lock.json

      - run: npm ci

      - name: Check Format
        run: npx nx format:check --base=origin/main

      - name: Run Frontend Checks
        run: npx nx run-many -t lint test build typecheck --projects=access-frontend
